### ISSUE TITLE
Erreurs lors du lancement des tests et de l'application

### ISSUE THREAD

**Issue by ericsiber** [egeorgel/FizzBuzz#1]
Le client a pourtant bien installé avec succès l'application via npm install et suivi la document .

Néanmoins, il obtient les erreurs suivantes sur son environnement de développement (node et npm étaient déjà installés, il n'a donc pas suivi les instructions) : 

Pour npm test : 

> > jasmine-node spec
> 
> /Users/esiber/Downloads/FizzBuzz-master/src/fizzBuzz.js:6
> class FizzBuzz {
> ^^^^^
> Exception loading: /Users/esiber/Downloads/FizzBuzz-master/spec/fizzBuzzSpec.js
> [SyntaxError: Unexpected reserved word]

Pour npm start : 

> > node src/main.js
> 
> /Users/esiber/Downloads/FizzBuzz-master/src/main.js:5
> let fizzMultiplen = "",
>     ^^^^^^^^^^^^^
> SyntaxError: Unexpected identifier
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3
> 
> npm ERR! Fizz-buzz@0.0.1 start: `node src/main.js`
> npm ERR! Exit status 8
> npm ERR! 
> npm ERR! Failed at the Fizz-buzz@0.0.1 start script.
> npm ERR! This is most likely a problem with the Fizz-buzz package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node src/main.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls Fizz-buzz
> npm ERR! There is likely additional logging output above.
> npm ERR! System Darwin 15.6.0
> npm ERR! command "node" "/usr/local/bin/npm" "start"
> npm ERR! cwd /Users/esiber/Downloads/FizzBuzz-master
> npm ERR! node -v v0.10.26
> npm ERR! npm -v 1.4.3
> npm ERR! code ELIFECYCLE
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /Users/esiber/Downloads/FizzBuzz-master/npm-debug.log
> npm ERR! not ok code 0

A-t-il raté un pré-requis ?

**Comment by egeorgel** [comment]
Yes you missed this part I think in the read me:
**You have to make sure that you have the last version of Node**, 
run :
`brew update`
 `brew upgrade node`

If you don't have [Homebrew](http://brew.sh) packages manageur run: 
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

**Comment by ericsiber** [comment]
Customer devs are running on top of Windows and production is on Linux Red Hat.
Could you please share the compatible range for node version ?

**Comment by egeorgel** [comment]
The node version is 6.2.2 and above
